name: build.yml
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - fork
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
      - name: Build release
        run: make release
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: release
          path: build/bin/*
