name: Release
on:
  release:
    types:
      - published

env:
  REGISTRY: us-central1-docker.pkg.dev/main-383408/otterize

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1