name: Release
on:
  release:
    types:
      - published

env:
  REGISTRY: us-central1-docker.pkg.dev/main-383408/otterize

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key_base64
          password: ${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON}}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: otterize
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: network=host

      - uses: actions/setup-go@v3

      - name: Build release
        run: make release

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: release
          path: build/bin/*

      - name: Build artifacts as Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.REGISTRY }}/rolesanywhere-credential-helper:${{ github.ref_name }},otterize/rolesanywhere-credential-helper:${{ github.ref_name }},otterize/rolesanywhere-credential-helper:latest
          push: true
          platforms: linux/amd64,linux/arm64
